### ISSUE TITLE
Automated update deps action is broken

### ISSUE THREAD

**Issue by dsimansk** [knative-sandbox/eventing-istio#57]
Per my comment on Slack:
https://cloud-native.slack.com/archives/C04LY4Y3EHF/p1690493604522879?thread_ts=1690468783.558009&cid=C04LY4Y3EHF

There's a race condition issue with execution of `update-deps.sh` and `update-codegen.sh` in this order. That's done in knobot's update deps for example. Due to the fact that `update-codegen.sh` is calling `update-deps.sh` without any flags at the end, it negates all the changes, because different version values are used etc.

Update: the broken part is git submodule update, that is being reset by the order of actions performed.

Knobot's action:
https://github.com/knative-sandbox/knobots/blob/3ab3f877f1440449a1d3e26e85052f2cefda1c01/actions/update-deps/entrypoint.sh#L54-L65

Codegen script:
https://github.com/knative-sandbox/eventing-istio/blob/bfed9ec22c1b25b4d4a679dc27664f3e426c48e5/hack/update-codegen.sh#L68-L69

/cc @pierDipi @creydr

**Comment by pierDipi** [comment]
Eventing does the same: https://github.com/knative/eventing/blob/ffa591593417f3e879a4834ddb87cc13e6cd3e05/hack/update-codegen.sh#L71-L72

**Comment by pierDipi** [comment]
serving as well: https://github.com/knative/serving/blob/0a3f5f96a8a599e1c060eb978590dc7a350292f4/hack/update-codegen.sh#L103-L104

**Comment by dsimansk** [comment]
IMO the issue is specifically in git submodules update. Because without executing fetch function the `git submodule --init --recursive` will reset the changes pulled by `update-deps.sh` script, i.e. diff is clean without additional changes.

**Comment by dsimansk** [comment]
Here's example of submodule being updated: https://github.com/knative-sandbox/knobots/actions/runs/5684668902/job/15407902127#step:6:234

But later when codegen is executed, the older version checked out again: https://github.com/knative-sandbox/knobots/actions/runs/5684668902/job/15407902127#step:6:3617

It's a side effect of no `git fetch` being performed and `git submodule --init --recursive` resetting the update.

**Comment by pierDipi** [comment]
I see, I'm not sure if we can simply remove  `git submodule --init --recursive`
